#!/bin/sh

# Set these paths appropriately

BIN="/Users/elina/Desktop/BA_code/TreeTagger/bin"
CMD="/Users/elina/Desktop/BA_code/TreeTagger/cmd"
LIB="/Users/elina/Desktop/BA_code/TreeTagger/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-spoken.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
