#!/bin/sh

# Set these paths appropriately

BIN="/Users/elina/Desktop/BA_code/TreeTagger/bin"
CMD="/Users/elina/Desktop/BA_code/TreeTagger/cmd"
LIB="/Users/elina/Desktop/BA_code/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/romanian-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/romanian.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
