#!/bin/sh

# Set these paths appropriately

BIN="/Users/elina/Desktop/BA_code/TreeTagger/bin"
CMD="/Users/elina/Desktop/BA_code/TreeTagger/cmd"
LIB="/Users/elina/Desktop/BA_code/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek-beta.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

